apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: pacman
spec:
  type: ClusterIP
  selector:
    app: pacman
    tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017