apiVersion: v1
kind: Service
metadata:
  name: pacman-service
  labels:
    app: pacman
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001
  selector:
    app: pacman
    tier: ui
