apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  labels:
    app: pacman
data:
  database_url: mongodb-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
  labels:
    app: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman
      tier: ui
  template:
    metadata:
      labels:
        app: pacman
        tier: ui
    spec:
      containers:
      - image: mattbator/pacman:latest
        name: pacman
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
        - name: MONGO_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
        - name: MONGO_AUTH_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: mongodb-secret
        - name: MONGO_AUTH_PWD
          valueFrom:
            secretKeyRef:
              key: password
              name: mongodb-secret
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          failureThreshold: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 1
          periodSeconds: 10
        readinessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /
            port: 8080