apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: my-first-namespace
spec:
  containers:
  - name: my-first-pod-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo "Hello (and Goodbye) World!"']
  restartPolicy: Never